### ISSUE TITLE
Cant install after recent update

### ISSUE THREAD

**Issue by Thavr0n** [SciPhi-AI/R2R-Dashboard#58]
**Describe the bug**
I can't build the app. 
![image](https://github.com/user-attachments/assets/3188b1bf-fb97-4008-a80e-4b78befa9bd6)

**To Reproduce**
git clone  https://r2r-docs.sciphi.ai/cookbooks/dashboard
cd R2R-Dashboard

pnpm install
pnpm build <-- this is where the Error happens.

**Expected behavior**
Build the app. It worked for me a week ago - just reset my project and it does not work any longer.

**Screenshots**
![image](https://github.com/user-attachments/assets/3188b1bf-fb97-4008-a80e-4b78befa9bd6)

**Desktop (please complete the following information):**

WSL
Visual Studio Code Terminal
Ubuntu 22

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NolanTrem** [comment]
Hey @Thavr0n thanks for flagging this. I've patched it in the most recent change.
