### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by jpetrantoni** [SciPhi-AI/R2R-Dashboard#61]
**Describe the bug**
Trying to fetch documents or run query
`Error fetching documents`

**To Reproduce**
docker-compose script

1. Go to 'localhost'
2. Click on the local deployment
3. Upload files
4. Refresh page and check console

**Expected behavior**
No error and normal file upload/query

**Screenshots**
<img width="1638" alt="Screenshot 2024-07-19 at 9 13 35 PM" src="https://github.com/user-attachments/assets/d49531d4-a10d-49ab-b422-994e5275e159">
<img width="1638" alt="Screenshot 2024-07-19 at 9 26 39 PM" src="https://github.com/user-attachments/assets/909d3a71-10df-4839-a782-18824321c3af">

**Desktop:**

- OS: macOS
- Browser Brave Chromium

**Comment by NolanTrem** [comment]
Hey @jpetrantoni thanks for flagging this. I've merged a fix. Seemed to have been an issue with our JS client.
